# Tensors

In [6]:
import tensorflow as tf
import numpy as np

In [12]:
sess = tf.InteractiveSession()
ten1 = tf.constant([[[1,2],[2,3]],[[30,4],[5,6]]])
print sess.run(ten1)
print ten1

x = tf.constant(np.random.rand(32).astype(np.float32))
y = tf.constant([1,2,3])

[[[ 1  2]
  [ 2  3]]

 [[30  4]
  [ 5  6]]]
Tensor("Const_6:0", shape=(2, 2, 2), dtype=int32)


In [13]:
tf.argmax(ten1, 2).eval()

array([[1, 1],
       [0, 1]])